#services:
#  pgvector:
#    image: 'pgvector/pgvector:pg16'
#    environment:
#      - 'POSTGRES_DB=ragDb'
#      - 'POSTGRES_PASSWORD=Pratik39'
#      - 'POSTGRES_USER=postgres'
#    labels:
#      - "org.springframework.boot.service-connection=postgres"
#    ports:
#      - '5432:5432'

services:
  postgres_container:
    image: 'pgvector/pgvector:pg16'
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pratik39
      POSTGRES_DB: ragDb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
